
/**
    CAT_CATALOGOS
**/

--PADRES
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('EPC','ESTATUS DE POLIZA O PAGO',NULL,'EPC','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TPG','TIPO DE PAGO',NULL,'TPG','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('100','PROCESO',NULL,'100','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('GEN','GENERO',NULL,'GEN','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ESPM','ESPECIALIDAD MEDICA',NULL,'ESPM','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('EP','ESTATUS POLIZA',NULL,'EP','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ENT','ENTIDAD FEDERATIVA',NULL,'ENT','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('CNV','CANAL DEL VENTA',NULL,'CNV','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('090','RUBROS',NULL,'90',NULL);
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('CMP','COMPAÑIAS',NULL,'CMP','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BNC','BANCOS',NULL,'BNC','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TCP','TIPO DE COBERTURA O PRODUCTO',NULL,'TCP','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TAS','TIPO ASEGURADO',NULL,'TAS','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('RUL','REGLAS',NULL,'RUL','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('RULE','REGLAS',NULL,'110',NULL);
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('PRO','TIPO PROVEEDOR',NULL,'PRO','1');
-- HIJOS
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('02EP','PAGADA','EP','2','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('101','CREAR USUARIO','100','101','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN02','AMERICAN EXPRESS BANK(MEXICO)','BNC','2','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TS03','GM INDIVIDUAL','TSG','3','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN09','Banco Base','BNC','9','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('CP04','METLIFE MÉXICO','CMP','S0034','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TS05','SALUD INDIVIDUAL','TSG','5','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('3CS','LABORATORIOS','RUL','3CS','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN01','ABC CAPITAL','BNC','1','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('103','ALERTA DE SERVICIO','100','103','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('01EP','EMITIDA','EP','1','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET01','AGUASCALIENTES','ENT','1','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN04','Banca Mifel','BNC','4','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('P05','COBERTURA DE GASTOS MEDICOS PO','TCP','5','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN10','Banco Compartamos','BNC','10','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('1CS','ASEGURADOS SINIESTROS','RUL','1CS','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TA02','CONYUGE','TAS','2','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TP90','OTRO','TPG','90','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('EM04','CIRUGIA GENERAL','ESPM','4','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('EM02','ANGIOLOGIA / CX VASCULAR','ESPM','2','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('CP03','SEGUROS ATLAS','CMP','S0023','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('CP05','ASEGURADORA INTERACCIONES','CMP','S0036','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('2M','PROCEDIMIENTOS NO ACORDES AL S','RUL','2M','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('CP06','SEGUROS MONTERREY NEW YORK LIF','CMP','S0038','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TP04','RENTA PERIÓDICA','TPG','4','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN03','BANCA AFIRME','BNC','3','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('R4M','CIE VS CPT4','RUL','4M','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('5CS','CUENTAS BANCARIAS','RUL','5CS','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('4CS','HOSPITALES','RUL','4CS','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('CP08','GRUPO NACIONAL PROVINCIAL','CMP','S0043','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('3M','TIEMPO DE RESOLUCION DEL PADEC','RUL','3M','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('2OII','COINCIDENCIAS CON OII ANTECEDE','RUL','2OII','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('CP11','VITAMÉDICA','CMP','H0710','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('EM08','GASTROENTEROLOGIA / CIRUGIA','ESPM','8','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('EM11','NEUMOLOGIA / CIRUGIA','ESPM','11','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('EM12','OFTALMOLOGIA /CIRUGIA','ESPM','12','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('2CS','MEDICOS','RUL','2CS','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('EM16','UROLOGIA/ CIRUGIA','ESPM','16','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('EM15','OTORRINOLARINGOLOGIA/ CIRUGIA','ESPM','15','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('2CE','AGENTES','RUL','2CE','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN08','Banco Azteca','BNC','8','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('1CE','ASEGURADOS EMISION','RUL','1CE','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('GE04','MASCULINO','GEN','M','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('P02','MUERTE COLECTIVO','TCP','2','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('P03','PERDIDAS ORGANICAS','TCP','3','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('P04','INDEMNIZACION POR INVALIDEZ AP','TCP','4','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('102','REPORTE CARGA','100','102','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('P06','COBERTURA DE GASTOS MEDICOS PO','TCP','6','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('GE03','DESCONOCIDO','GEN','D','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('GE01','FEMENINO','GEN','F','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('P07','GM INDEMNIZATORIO','TCP','7','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('P10','PREVENCION','TCP','10','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET03','BAJA CALIFORNIA SUR','ENT','3','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('PR04','FARMACIA','PRO','4','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET02','BAJA CALIFORNIA','ENT','2','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('1M','PROCEDIMIENTOS NO ACORDES A LA','RUL','1M','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('EM14','ORTOPEDIA Y TRAUMATOLOGIA/ CIR','ESPM','14','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('EM13','ONCOLOGIA MEDICA / CIRUGIA','ESPM','13','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('R1M','PROCEDIMIENTOS NO ACORDES A LA','RUL','1M','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('R4D','ASEGURADOS EMISION','RUL','4D','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('EM10','NERVIOSO /CIRUGIA','ESPM','10','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('EM09','GINECOLOGIA ONCOLOGICA','ESPM','9','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TA01','TITULAR','TAS','1','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('EM07','ENDOCRINOLOGIA','ESPM','7','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('EM06','COLOPROCTOLOGIA','ESPM','6','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN05','Banco Actinver','BNC','5','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('EM05','CIRUGIA PLASTICA, ESTETICA  Y','ESPM','5','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN07','Banco Autofín México','BNC','7','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('EM03','CARDIOLOGIA / CIRUGIA','ESPM','3','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('1OII','COINCIDENCIAS CON OII FALLECIM','RUL','1OII','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('EM01','ANESTESIA','ESPM','1','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('CP10','SALUD BANCOMER','CMP','H0704','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('CP09','AXA SEGUROS','CMP','S0048','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TP02','REEMBOLSO','TPG','2','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('CP07','MAPFRE TEPEYAC','CMP','S0041','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TS04','GM COLECTIVO','TSG','4','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TP03','INDEMNIZATORIO','TPG','3','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('CP02','SEGUROS INBURSA','CMP','S0022','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('CP01','SEGUROS BANORTE','CMP','S0001','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TS06','SALUD COLECTIVO','TSG','6','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TS02','AP COLECTIVO','TSG','2','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN06','Banco Ahorro Famsa','BNC','6','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TS01','AP INDIVIDUAL','TSG','1','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TP01','PAGO DIRECTO','TPG','1','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TA03','HIJO/HIJA','TAS','3','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('R8M','PROCLIVES A FRAUDE SI OCURRE E','RUL','8M','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('R9M','CIE 10 QUE SE RELACIONAN A CX','RUL','9M','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('R7M','MONTO MEDIO DEL PROCEDIMIENTO(','RUL','7M','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('R6M','DIAS DE ESTANCIA HOSPITALARIA','RUL','6M','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('03EP','MODIFICADA','EP','3','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('R5M','PADECIMIENTOS Y PROOVEDOR NO A','RUL','5M','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('R3M','TIEMPO DE RESOLUCION DEL PADEC','RUL','3M','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('R3D','CUENTAS BANCARIAS DUPLICADAS','RUL','3D','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('R2M','PROCEDIMIENTOS NO ACORDES AL S','RUL','2M','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('R2D','SINIESTROS DUPLICADOS','RUL','1D','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('R11M','CUENTA BANCARIA','RUL','11M','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('R1D','FACTURAS DUPLICADAS','RUL','1d','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('R10M','CONDICIONADO A LAS CARACTERIST','RUL','10M','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('PR90','OTRO','PRO','90','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('PR11','PROVEEDOR DE TERAPIAS','PRO','11','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('PR10','PROVEEDOR APARATOS PARA OÍDO','PRO','10','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('PR09','PROVEEDOR APARATOS PARA VISTA','PRO','9','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('PR07','SERVICIOS DE ASISTENCIA','PRO','7','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('PR06','AMBULANCIA','PRO','6','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('PR08','PROVEEDOR APARATOS ORTOPÉDICOS','PRO','8','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('PR05','LABORATORIO','PRO','5','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('PR01','HOSPITAL','PRO','1','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('PR03','ENFERMERA','PRO','3','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('P90','OTROS','TCP','90','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('PR02','MÉDICO','PRO','2','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('P08','BASICO ESTANDARIZADO','TCP','8','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('P09','DENTAL','TCP','9','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('P01','MUERTE ACCIDENTAL','TCP','1','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET04','CAMPECHE','ENT','4','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET09','DISTRITO EDERAL','ENT','9','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET08','CHIHUAHUA','ENT','8','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET07','CHIAPAS','ENT','7','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET06','COLIMA','ENT','6','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET10','DURANGO','ENT','10','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET05','COAHUILA','ENT','5','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET12','GUERRERO','ENT','12','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET11','GUANAJUATO','ENT','11','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET14','JALISCO','ENT','14','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET13','HIDALGO','ENT','13','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN90','OTRO','BNC','90','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN11','Banco Credit Suisse (México)','BNC','11','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN12','Banco del Bajío','BNC','12','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN13','Banco Inbursa','BNC','13','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN14','Banco Inmobiliario Mexicano','BNC','14','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN15','Banco Interacciones','BNC','15','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN16','Banco invex','BNC','16','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN17','Banco JP Morgan','BNC','17','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN18','Banco Mercantil del Norte','BNC','18','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN19','Banco Monex','BNC','19','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN20','Banco Multiva','BNC','20','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN21','Banco nacional de Mexico','BNC','21','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN22','Banco Paga Todo','BNC','22','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN23','Banco Progreso Chihuahua','BNC','23','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN24','Banco Regional de Monterrey','BNC','24','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN25','Banco Santander','BNC','25','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN26','Banco Ve por Más','BNC','26','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN27','Banco Wal Mart de México Adela','BNC','27','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN28','BanCoppel','BNC','28','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN29','BANCREA','BNC','29','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN30','Bank of America México','BNC','30','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN31','Bank of Tokyo Mitsubishi UFJ','BNC','31','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN32','Bankaool','BNC','32','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN33','BANSÍ','BNC','33','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN34','Barclays Bank México','BNC','34','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN35','BBVA Bancomer','BNC','35','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN36','CI Banco','BNC','36','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN37','Consubanco','BNC','37','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN38','Deutsche Bank México','BNC','38','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN39','Fundación Dónde México','BNC','39','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN40','HSBC México','BNC','40','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN41','Intercam banco','BNC','41','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN42','Investa Bank','BNC','42','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN43','Scotiabank','BNC','43','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN44','UBS Bank México','BNC','44','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('BN45','Volkswagen Bank','BNC','45','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET15','Estado de México','ENT','15','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET16','Michoacán','ENT','16','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET17','Morelos','ENT','17','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET18','Nayarit','ENT','18','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET19','Nuevo León','ENT','19','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET20','Oaxaca','ENT','20','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET21','Puebla','ENT','21','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET22','Querétaro','ENT','22','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET23','Quintana Roo','ENT','23','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET24','San Luis Potosí','ENT','24','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET25','Sinaloa','ENT','25','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET26','Sonora','ENT','26','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET27','Tabasco','ENT','27','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET28','Tamaulipas','ENT','28','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET29','Tlaxcala','ENT','29','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET30','Veracruz','ENT','30','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET31','Yucatán','ENT','31','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET32','Zacatecas','ENT','32','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET33','Extranjero','ENT','33','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('ET34','Desconocido o sin domicilio','ENT','34','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TA04','Ascendiente','TAS','04','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TA05','Padre / Madre','TAS','05','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TA06','Hermano / Hermana','TAS','06','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TA07','Tío / Tía','TAS','07','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TA08','Abuelo / Abuela','TAS','08','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TA09','Nieto / Nieta','TAS','09','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TA10','Sobrino/ Sobrina','TAS','10','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TA90','Otro','TAS','90','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('TA99','Ninguno','TAS','99','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('AMIS','Administrador AMIS','CMP','AMIS','1');
INSERT INTO CAT_CATALOGOS (CatalogoId,DescripcionCatalogo,CatalogoPadreId,CatalogoValor,CatalogoActivo) VALUES ('CP12','GENERAL DE SALUD','CMP','H0707','1');

COMMIT;
