INSERT INTO CAT_SISTEMAS_CATALOGOS (FK_SistemaId,FK_CatalogoId) VALUES (
1,'100');
INSERT INTO CAT_SISTEMAS_CATALOGOS (FK_SistemaId,FK_CatalogoId) VALUES (
1,'BNC');
INSERT INTO CAT_SISTEMAS_CATALOGOS (FK_SistemaId,FK_CatalogoId) VALUES (
1,'CMP');
INSERT INTO CAT_SISTEMAS_CATALOGOS (FK_SistemaId,FK_CatalogoId) VALUES (
1,'CNV');
INSERT INTO CAT_SISTEMAS_CATALOGOS (FK_SistemaId,FK_CatalogoId) VALUES (
1,'ENT');
INSERT INTO CAT_SISTEMAS_CATALOGOS (FK_SistemaId,FK_CatalogoId) VALUES (
1,'EP');
INSERT INTO CAT_SISTEMAS_CATALOGOS (FK_SistemaId,FK_CatalogoId) VALUES (
1,'EPC');
INSERT INTO CAT_SISTEMAS_CATALOGOS (FK_SistemaId,FK_CatalogoId) VALUES (
1,'ESPM');
INSERT INTO CAT_SISTEMAS_CATALOGOS (FK_SistemaId,FK_CatalogoId) VALUES (
1,'GEN');
INSERT INTO CAT_SISTEMAS_CATALOGOS (FK_SistemaId,FK_CatalogoId) VALUES (
1,'PRO');
INSERT INTO CAT_SISTEMAS_CATALOGOS (FK_SistemaId,FK_CatalogoId) VALUES (
1,'TAS');
INSERT INTO CAT_SISTEMAS_CATALOGOS (FK_SistemaId,FK_CatalogoId) VALUES (
1,'TCP');
INSERT INTO CAT_SISTEMAS_CATALOGOS (FK_SistemaId,FK_CatalogoId) VALUES (
1,'TPG');
INSERT INTO CAT_SISTEMAS_CATALOGOS (FK_SistemaId,FK_CatalogoId) VALUES (
1,'TSG');
