INSERT INTO ESPECIALIDAD (Cve,Descripcion) VALUES (
'1','AFECC PERINATAL');
INSERT INTO ESPECIALIDAD (Cve,Descripcion) VALUES (
'10','NEOPLASIAS');
INSERT INTO ESPECIALIDAD (Cve,Descripcion) VALUES (
'11','NERVIOSO');
INSERT INTO ESPECIALIDAD (Cve,Descripcion) VALUES (
'12','OIDO');
INSERT INTO ESPECIALIDAD (Cve,Descripcion) VALUES (
'13','OJO');
INSERT INTO ESPECIALIDAD (Cve,Descripcion) VALUES (
'14','OSTEMUSCULAR');
INSERT INTO ESPECIALIDAD (Cve,Descripcion) VALUES (
'15','PIEL');
INSERT INTO ESPECIALIDAD (Cve,Descripcion) VALUES (
'16','RESPIRATORIO');
INSERT INTO ESPECIALIDAD (Cve,Descripcion) VALUES (
'17','INMUNO');
INSERT INTO ESPECIALIDAD (Cve,Descripcion) VALUES (
'18','TRAUMA Y OTRAS');
INSERT INTO ESPECIALIDAD (Cve,Descripcion) VALUES (
'2','CARDIO');
INSERT INTO ESPECIALIDAD (Cve,Descripcion) VALUES (
'3','CONGENITAS');
INSERT INTO ESPECIALIDAD (Cve,Descripcion) VALUES (
'4','DIGESTIVO');
INSERT INTO ESPECIALIDAD (Cve,Descripcion) VALUES (
'5','PARTO');
INSERT INTO ESPECIALIDAD (Cve,Descripcion) VALUES (
'6','ENDOCRINO');
INSERT INTO ESPECIALIDAD (Cve,Descripcion) VALUES (
'7','GENITURINARIO');
INSERT INTO ESPECIALIDAD (Cve,Descripcion) VALUES (
'8','INFECCIOSAS');
INSERT INTO ESPECIALIDAD (Cve,Descripcion) VALUES (
'9','MENTALES');
COMMIT;