INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'','01','01','03','LABORATORIO DE PATOLOGIA CLINICA SANTA ANITA','CLINICA/LABORATORIO SANTA ANITA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'AASA740122PL5','07','01','02','ANTONIO ALVAREZ SAQUI','HOSPITAL SAN LUCAS','A');
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'AASC7012054C9','30','01','01','CESAR ANDRADE SEPULVEDA','CENTRO HOSPITALARIO  "CABALLERO" CENTRO GINECOLOGICO Y OBSTETRICO MOULIN','A');
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'AASM711128BZ3','15','01','02','HOSPITAL CENTRO MEDICO DE ORIENTE',' MANUEL ARANDA SOTO',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'ACF430605RN4','05','01','03','ASOCIACION CIVIL FILANTROPICA Y EDUCATIVA, A.C.','SANATORIO ADVENTISTA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'AEM150625BZ4','09','01','03','AVR EspecialidadES MEDICAS S.C.','',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'AETP481204K8I','04','01','02','PEDRO ACEVEDO TORRES','CLINICA DE EspecialidadES IZTACALA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'AGA090223JD1','18','01','01','ADMINISTRADORA GALENO, S.A. DE C.V.','HOSPITAL SAN RAFAEL',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'AHT110303JR6','26','01','01','ADMINISTRACION DE HOSPITALES TLALNEPANTLA, S.A. DE C.V.','MEDICA LEO',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'AIM080407EG1','12','01','02','ASOCIACION INTEGRAL MEDICO HOSPITALARIA, S.C.','ASOCIACION INTEGRAL MEDICO HOSPITALARIA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'APS121106N1A','06','01','01','ARQUITECTURA Y PROYECTOS SUSTENTABLES MZ, S.A DE C.V','RIOBAMBA HOSPITAL BOUTIQUE',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'BAZG570331IHO','16','01','03','BARRAGAN ZUNIGA GUILLERMO','CENTRAL MEDICO QUIRURGICA DR. BARRAGAN',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'BEM120602K81','02','01','01','BEGUSA EspecialidadES MEDICAS, S.C.','BEGUSA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CAMM720409356','31','01','03','MANUEL DE JESUS CANCINO MALDONADO','CENTRO MEDICO DE EspecialidadES GARTELL',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CAR020405UK2','21','01','01','CENTRO DE ATENCION RENAL ESPECIALIZADA VIDA Y TRASPLANTE SC','CLINICA DE HEMODIALISIS HEALTH SATELITE',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CCE070521JU6','08','01','04','CEMIN COORDINADORA DE EMPRESAS INDEPENDIENTES, S.A. DE C.V.','MUNDO CLARO',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CCQ101110GN7','11','01','02','CENTRO CLINICO QUIRURGICO ESCANDON, S.C.','CLINICA ZAR',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CCS080404LL9','21','01','02','CLINICA CHULAVISTA SERVICIOS DE SALUD, S.A. DE C.V.','CLINICA CHULAVISTA SERVICIOS DE SALUD, S.A. DE C.V.',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CEI1006093K0','08','01','03','CORPORATIVO DE EspecialidadES IMPULSORA, S.A. DE C.V.',' CLINICA DE EspecialidadES MICHELLE',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CEM9509084Z8','13','01','03','CLINICA DE EspecialidadES MEDICAS SUR, S.C.','HOSPITAL TLALPAN',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CEO000313S47','19','01','01','CENTRO DE EspecialidadES EN OFTALMOLOGIA, A.C.','CENTRO DE EspecialidadES EN OFTALMOLOGIA, A.C.',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CFU071115D34','05','01','02','CLINICA FUTURA, S.A. DE C.V.','CLINICA MEDICA FUTURA, S.A. DE C.V.',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CIO090217C14','31','01','02','CENTRO INTEGRAL DE OFTALMOLOGÍA BROWN Y FERRER S.A. DE C.V.','OPTIKLASER',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CIS120328GJ3','03','01','04','CLINICA INTEGRAL EN SALUD','',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CKC060512FI7','16','01','02','CLINI K DE CIRUGIA AVANZADA SA DE CV  ','MAG MEDICAL ? MEDICAL AMBULATORY GROUP',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CLG8512022V7','04','01','02','CLINICA DE LEON Y GARZA S.A. de C.V.','CLINICA DE LEON Y GARZA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CMA090616KC0','02','01','01','CENTRO MEDICO LA AURORA, S. DE RL','CENTRO MEDICO LA AURORA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CMC130311CZ0','09','01','04','CORPORATIVO DE MEDICINA Y CIRUGIA ESPECIALIZADA, S.A. DE C.V.','MEDICA LOMAS',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CME011015E27','20','01','02','CENTRO MEDICO DE EspecialidadES  ATLACOMULCO, S.A. DE C.V.','CENTRO MEDICO DE EspecialidadES  ATLACOMULCO, S.A. DE C.V.',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CME030124LZ1','06','01','04','CLASE MEDICA, S.A. DE C.V.','HOSPITAL MEDICA LONDRES (ANTES CLINICA MEDICA LONDRES )',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CMG1402198Q0','06','01','02','CORPORATIVO MEDICO GEMA, S.A. DE C.V.','MEDICAL DIAGNOSTIC',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CMH120312IG9','10','01','04','CORPORATIVO MEDICO HANY, S.C.','SANCHEZ-ZUÑIGA RODRIGUEZ ERIKA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CMIO71004FE0','22','01','03','CONSORCIO MEDICO INTEGRAL, S.C.','CONSORCIO MEDICO INTEGRAL, S.C.',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CMM920610VA1','06','01','03','CLINICA MITRAS','CENTRO MEDICO MITRAS',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CMQ600819R6A','10','01','04','CENTRO MEDICO QUIRURGICO DOCTOR FRANCISCO MONTES DE OCA, S.A. DE C.V.','Sanatorio Montes de Oca',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CNE020620238','19','01','02','CLINICA DE NEUROTRAUMATOLOGIA','CLINICA DE NEUROTRAUMATOLOGIA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'COGM500207QV7','02','01','04','CLINICA MEDICA CHOPERENA','CLINICA MEDICA CHOPERENA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'COOH7808039E1','02','01','01','HECTOR ADRIÁN CORRAL OSORNIO','',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CP5120117Y25','16','01','04','','',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CPS120117T25','07','01','03','CORPORACION PROFESIONAL EN SALUD COPROSA, S.A. DE C.V.','CORPROSA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CQE081126CB1','32','01','02','CENTRO QUIRURGICO ESMERALDA','CENTRO QUIRURGICO ESMERALDA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CQR070514DU9','10','01','01','CENTRO QUIRURGICO RIO CONSULADO','HOSPITAL RIO CONSULADO',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CRO031211PS4','08','01','03','','',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CROR731001IX6','07','01','02','CLINICA DE RADIOTERAPIA DE OCCIDENTE, S.A. DE C.V.','CLINICA DE RADIOTERAPIA DE OCCIDENTE',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CSI070705K82','04','01','02','','',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CSM1209131UA','13','01','02','CONSORCIO EN SERVICIOS MEDICOS SEMJOR, S.A. DE C.V.','CONSORCIO EN EspecialidadES MEDICAS RPR',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CSM140509E58','08','01','02','COMERCIALIZADORA DE SERVICIOS MÉDICOS SIPE, S.A DE C.V.','COMERCIALIZADORA DE SERVICIOS MÉDICOS SIPE',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CSO980216A92','31','01','03','CRIOGENETICA DE SONORA, S.A. DE C.V.','CRYO-GEN SONORA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CTO060214NB9','08','01','03','CLINICA TORRES, S.C.','CLINICA TORRES',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CTO620214NB9','09','01','04','','',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CUC090708JGA','21','01','01','CLINICA MEDICA UCECAE, S.A. DE C.V.','UNIDAD DE CORTA ESTANCIA DE ALTA Especialidad',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'CVI971218J36','08','01','04','HOSPITAL CLINICA VIVEROS','CLINICA VIVEROS',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'DSO080430MB0','05','01','02','CENTRO OFTALMOLOGICO SATELITE
2. GNP. DERCAL SOLUCIONES SA DE CV
','DERCAL / LASER',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'FLC071018QJ1','14','01','01','','FACOLASER CENTRO DE OFTALMOLOGIA AVANZADA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'FMA181021Q26','14','01','04','FUNDACION MARIA ANA MIER DE ESCANDON IAP','HOSPITAL ESCANDON',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'FSG7712283P5','07','01','03','FUNDACION SANTOS Y DE LA GARZA EVIA I.B.','CENTRO MEDICO HOSPITAL SAN JOSE (SAN JOSE TEC DE MONTERREY)',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'GAK121222T16','12','01','04','Grupo Axioma Kusuri SA de CV','AXIOMA CENTRO MÉDICO',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'GEM870812UIA','20','01','01','GRUPO DE ESPECIALISTAS MEDICOS ASOCIADOS DE SANTA MONICA','HOSPITAL G.E.M.A',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'GHA140903NG9','03','01','03','GRUPO HOSPITALARIO ALIJADORES','GRUPO HOSPITALARIO ALIJADORES',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'GHE081222255','20','01','02','GRUPO HOSPITALARIO EFRATA, S.A. DE C.V.','HOSPITAL EFRATA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'GM051020J31','24','01','03','MEDICAL & HOSPITAL S.A DE C.V','GALO MEDICAL & HOSPITAL',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'GML1309063J4','26','01','03','SANATORIO Y MATERNIDAD ELIHER','SANATORIO Y MATERNIDAD ELIHER',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'GMO080211GP3','23','01','04','GRUPO MEDICO ORTIZ PEREZ S.C.','MEDICA INTEGRAL',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'GNM080819BMA','23','01','03','GRUPO NOE MED, S.A. DE C.V.','NOEMED',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'GOOE550410IN7','06','01','03','EZEQUIEL PASCUAL GOMEZ OLIVER','CLINICA DE EspecialidadES MEDICAS SAN JUDAS TADEO',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'GURL680618FV','14','01','03','LETICIA GUTIERREZ ROJAS','CLINICA SANTA MONICA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'GUSB551205SUS','05','01','02','BEGUSA CLINICA DE EspecialidadES MEDICAS A.C.','BEGUSA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HAP870317T82','25','01','04','HOSPITAL ANGELES DEL PEDREGAL, S.A. DE C.V.','HOSPITAL ANGELES DEL PEDREGAL',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HCO730301UB7','09','01','03','HOSPITAL Y CLINICA OCA, S.A. DE C.V.','DOCTORS HOSPITAL',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HCU910827CTA','13','01','01','HOSPITAL CHURUBUSCO, S.A. DE C.V.',' HOSPITAL CHURUBUSCO',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HEB0203195UA','23','01','02','HOSPITAL DE EspecialidadES BOSQUES DE ARAGON, S.A. DE C.V.','HOSPITAL DE EspecialidadES BOSQUES DE ARAGON',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HEGF800308298','19','01','04','JOSE FRANCISCO HERNANDEZ GARCIA','CLINICA DE JESUS',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HEM710820UE0','26','01','01','HOSPITAL DE EspecialidadES MIG, S.A. DE C.V.','HOSPITAL DE EspecialidadES MIG, S.A DE C.V.',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HEVE550525KL5','30','01','04','HERRERA VIVIAN MARIA ESTELA','CLINICA GEN',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HFA850516540','19','01','04','HOSPITAL FATIMA SA DE CV','HOSPITAL FATIMA SA DE CV',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HHX040325NQ4','14','01','02',' HOSPITALES H, S.A. DE C.V.','HOSPITAL DIOMED',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HIP920225QG2','31','01','02','HOSPITAL INFANTIL PRIVADO DE ACAPULCO, S.A. DE C.V.','HOSPITAL DEL PACIFICO',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HJE0806278DA','17','01','04','HOSPITAL FAMILU SA CV','HOSPITAL JERUSALEN ECATEPEC',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HJO990615NZ8','22','01','02','CONSULTORIO MÉDICO HOSPITAL JOCARDIMI, S.A. DE C.V.','CONSULTORIO MÉDICO HOSPITAL JOCARDIMI, S.A. DE C.V.',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HME970516-IT9','27','01','04','HOSPITAL MERLOS SA DE CV','HOSPITAL MERLOS',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HMI951115GI3','24','01','03','HECTOR ANDRES NAVA GARCIA  INTEGRA','INTEGRA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HMU070821G21','27','01','01','HOSPITAL MULTIMEDICA, S.A.  DE C.V.','HOSPITAL MULTIMEDICA, S.A.  DE C.V.',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HNM130821K90','23','01','02','HOSPITAL NOVUS MEDICA, S.C.','CLINICA SAN MARCOS',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HPE060525UB8','10','01','01','HOSPITAL PRIVADO ECATEPEC','HOSPITAL PRIVADO ECATEPEC',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HRO110311AA','03','01','01','CLINICA MEDICA ROBLES LOPEZ, S.A. DE C.V.
2.GNP. CLINICA FUTURA SA DE CV','ROLOSA COACALCO
2. GNP. CLÍNICA ROLOSA, FUTURA Y BETHESDA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HSA040325SK9','24','01','03','HOSPITAL SANTIAGO APOSTOL','HOSPITAL SANTIAGO APOSTOL',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HSC021105D5A','07','01','04','HOSPITAL SANTA CECILIA DE MONTERREY SA DE CV','CLINICA SANTA CECILIA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HSG091002771','22','01','02','HOSPITAL SAN GABRIEL ARCANGEL, S.A. DE C.V.','HOSPITAL SAN GABRIEL ARCANGEL',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HSL940816K50','11','01','01','HOSPITAL SAN LUCAS DE MONTERREY, S.A. DE C.V.','HOSPITAL SAN LUCAS',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'HTE010404IZ2','30','01','02','HOSPITAL  DE TRAUMATOLOGIA Y EspecialidadES MEDICAS  SAN JOSE S.A. DE C.V.','HOSPITAL  DE TRAUMATOLOGIA Y EspecialidadES MEDICAS  SAN JOSE S.A. DE C.V.',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'IAM0608036L4','25','01','04','IGG ASOCIACION MEDICA ESPECIALIZADA, S.C.','INSUMOS MEDICINALES LEMER',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'IES1103283F8','25','01','01','INTEGRACION DE ESPECIALISTAS EN SALUD LA JOLLA, S.A. DE C.V.','CLINICA LA JOLLA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'IIE961004BH0','06','01','02','IECO, INSTITUTO DE ENFERMEDADES Y CIRUGIA OCULAR','IECO, INSTITUTO DE ENFERMEDADES Y CIRUGIA OCULAR',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'IIS070524MNA','16','01','04','','',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'IMC141027LB2','20','01','01','INSTITUTO MEXICANO DEL CUIDADO AVANZADO DE HERIDAS S.A. DE C.V.','INSTITUTO MEXICANO DEL CUIDADO AVANZADO DE HERIDAS S.A. DE C.V.',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'IME1003261CA','01','01','04','31 MEDICAL, S.A. DE C.V.','CLINICA ZAR',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'IMV030513DN4','28','01','02','INSTITUTO MEDICO DE LA VISION  S.A. DE C.V.','INSTITUTO MEDICO DE LA VISION',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'INF031010RP4','13','01','01','INFOLOGIX','SANATORIO MARIANO',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'LECF490601SY6','12','01','01','FERNANDO LEON CERVANTES','CLINICA DR. LEON',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'LERG710906RX0','32','01','03','CENTRO QUIRURGICO ROMANO','CENTRO QUIRURGICO ROMANO',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'LHA160401FI3','11','01','03','LIVI HALSA','',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'LICR4109057M5','25','01','03','LIMA DE LA CRUZ RUBEN','CLINICA MEDICA LIDAV',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'LOL990115EE2','18','01','04','LASER OCULAR LOMAS, S.C.','LASER OCULAR LOMAS',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'LUM810305CI1','24','01','04','CLINICA MEDICA CRISTO REY','CRISTO REY LUMAEL',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'LUMF760603M83','01','01','04','FERMIN DE LA LUZ MORALES','',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'LUMF760603MB3','29','01','01','','HOSPITAL OYOLA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'LUSI5809146I4','18','01','03','DINAMICA MEDICA HOSPITALARIA, S.A. DE C.V.','',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'MAE0804237D3','29','01','02','MEDICINA ALTA Especialidad S.C.','MEDICINA ALTA Especialidad S.C.',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'MCL020510BE0','15','01','03','ISEME, INTEGRACION DE SERVICIOS MEDICOS, S.C.','MUNDO CLARO',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'MCM110913R15','28','01','02','MED-LUD CUIDADOS MEDICOS PERSONALIZADOS, S.C.','MED-LUD',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'MED091013NI2','03','01','02','MEDIZCALLI, S.C.','CLINICA SAN JOSE,  S.C.',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'MED980923JP5','07','01','04','MEDILAP, S.A. DE C.V.','MEDICA SAN LUIS',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'MPO051205HZ2','20','01','01','MEDICA DEL PORTAL S.C.','CLINICA MEDICA DEL PORTAL',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'MQS960320NX2','17','01','03','SOCIEDAD MEDICO QUIRURGICA DE SAN JOSE ITURBIDE, S.A. DE C.V.','SOCIEDAD MEDICO QUIRURGICA DE SAN JOSE ITURBIDE',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'MSP091130B57','27','01','02','MEDICA SPACE, S.A. DE C.V.','MEDICAL SPACE',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'NHM921119HA0','16','01','03','NUCLEO HOSPITALARIO MED., S.A. DE C.V.','NUCLEO HOSPITALARIO MED',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'OCM140901IQ2','10','01','04','OVM CORPORATIVO MEDICO QUIRURGICO PEDREGAL S.C.','',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'OEM990629IP0','01','01','01','OPERADORA DE EspecialidadES MEDICO QUIRURGICAS PLAZA IZCALLI, S.A. DE C.V.','MEDICA SAN MARCOS',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'OIRE731205QYA','17','01','01','EVA MARIA ORTIZ RAMIREZ','MEDICA SAN ISIDRO',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'OSA0303263J8','23','01','03','OPERADORA SAN ANGEL INN, S.A DE C.V','HOSPITAL SAN ANGEL INN',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'OSS080331528','22','01','02','OPERADORA DE SERVICIOS DE SALUD SANTA LUCIA SA.. DE C.V.','HOSPITAL SANTA LUCIA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'PCS120925AU3','09','01','04','','CLINICA PATRIOTISMO',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'PDM9507124Y5','30','01','03','PRUEBAS DIAGNOSTICAS MEDICAS DEL VALLES S.C.','PRUEBAS DIAGNOSTICAS MEDICAS DEL VALLE S.C.',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'PGX100721P35','25','01','04','PROSALUD G4 S DE RL DE CV','PROSALUD G4',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'PMB080407EUA','11','01','04','PRESTA SERVICIOS MEDICOS DEL BAJIO S.A. DE C.V.','',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'PMG1509119H7','01','01','03','PROPIA MEDICAL GERI, S.A. DE C.V.','HOSPITAL PRIVADO DE ECATEPEC',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'PPS110214N24','11','01','01','PROMEDICIN GUCAM, S.C.','PROMEDICIN, SERVICIOS MEDICOS INTEGRALES',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'PSU8701274U4','21','01','03','POLICLINICA DEL SUR, S.A.','POLICLINICA DEL SUR',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'RAAR770430TE5','24','01','04','RAMON RAMIREZ ALVARADO','CLINICA RHIYALV',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'RCE1208024I3','12','01','02','CONSORCIO EN EspecialidadES MEDICAS, S.A. DE C.V.','CONSORCIO EN EspecialidadES MEDICAS',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'RDM090508K1A','12','01','01','RGI DESARROLLO MEDICO (DISTRITO FEDERAL)','RGI DESARROLLO MEDICO SC',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'RFJ000828908','05','01','01','RENDIMIENTO FISICO DE JALISCO','MUNDO FISICO',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'ROFE5803273CA','28','01','01','JOSE ELOY RODRIGUEZ FRANCO','SANATORIO SANTA ROSA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'ROGJ650825KA5','26','01','04','ROSAS GRANADOS JUAN LUIS','CLINICA DEL ANGEL',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'SAS120724MT4','13','01','02','SALUD ANGELES DE SAN RAFAEL, S.A. DE C.V.','MEDICA NORTE',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'SAVL551230MGO','18','01','01','LEOPOLDO SANCHEZ VALLE Y COPS','HOSPIMEDICA CAROLINA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'SESL650713J38','18','01','04','LILIA CARMEN SERVIEN SANCHEZ','ADMINISTRACION DE SERVICIOS HOSPITALARIOS',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'SIM091026U26','14','01','02','SALUD INTEGRA MOCTEZUMA, S.C.','CLINICA HORUS / HORUS CLINICA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'SME001012RI2','32','01','04','STAR MEDICA S.A. DE C.V.','STARMEDICA SAN LUIS',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'SME0608231D6','26','01','03','SERVICIOS MEDICOS Y DE EQUIPAMIENTO, S.A. DE C.V.','SERME / HOSPITAL DE NEFROLOGIA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'SMO0802271M3','05','01','01','HOSPITAL MARIA AUXILIADORA SERVICIOS MEDICOS OMEGA  SAPI DE CV','HOSPITAL MARIA AUXILIADORA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'SOC410610U24','21','01','02','CLINICA SOROAL, S.A. DE C.V.','CLINICA SOROAL',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'SODR630120','01','01','04','RAMON GERARDO SORIANO DIAZ','CLINICA MEDICA HUMANA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'SOM871230J91','19','01','01','SANATORIO OFTALMOLOGICO MERIDA, S.A. DE C.V.','SANATORIO OFTALMOLOGICO MERIDA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'SSA831021RSO','31','01','04','SANATORIO SAN AGUSTIN','SANATORIO SAN AGUSTIN',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'SSJ530921BT5','09','01','01','CENTRO DE EspecialidadES MEDICAS SAN JOSE','HOSPITAL (SANATORIO) SAN JOSE',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'SSM000504935','15','01','03','SANATORIO Y SERVICIOS MEDICOS OBREGON, S.A. DE C.V.','HOSPITAL OBREGON CORPROSA',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'TCM120629815','02','01','03','PREVEMED TCMG-SALUD S.A. DE C.V.','TCMG-SALUD',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'TMC1002084X6','22','01','04','TORRE MEDICA CUEMANCO','TORRE MEDICA CUEMANCO',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'TOVJ450516LZ5','32','01','04','JUAN JOAQUIN TORRES VELAZQUEZ','CLÍNICA NARVARTE',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'UEM0005248G3','29','01','03','UNION DE EspecialidadES MEDICAS, S.C.','MEDICA SAN MARCOS',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'UHP741210IZ6','17','01','04','UNIDAD HOSPITALARIA LA PAZ, S.A. DE C.V.','UNIDAD HOSPITALARIA LA PAZ',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'UIMY49061073A','27','01','01','URIBE MONTECINOS YOLANDA','CLINICA RIVA PALACIO',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'UNI090331CF2','15','01','04','UNIDAD DE NEUROCIENCIAS INTEGRALES, S.C.','CENTRO DE NEUROCIENCIAS INTEGRALES SC',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'UQM951204TE6','32','01','03','UNIDAD QUIRURGICA MONTGOBER, S.A. DE C.V.','UNIDAD QUIRURGICA MONTGOBER, S.A. DE C.V.',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'URG100524IZ6','04','01','01','URGEMEDIC, S.C.','URGEMEDIC, S.C. AMBULANCIAS TERRESTRES AEREAS',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'VIGD811031HA7','10','01','03','CURVES & PERFECT BODY CLINICA DE CIRUGIA DE CORTA ESTANCIA, MEDICINA ESTETICA Y LONGEVIDAD','CURVES & PERFECT BODY',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'WSC080327U78','28','01','01','WTC SPORT CLINIC AMBULATORIAS SA DE CV','SPORT CLINIC AMBULATORIAS SA DE CV',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'YAEP440115NV0','04','01','04','PEDRO YABUR ELIAS','CENTRO MEDICO VILLA DE LAS FLORES',NULL);
INSERT INTO PROVEEDOR (Rfc,ClaveEntidad,TipoProveedor,Especialidad,Nombre,Alias,TipoRiesgo) VALUES (
'YCO101214PT4','15','01','02','Yanxander Corp, S.A. de C.V','Clínica de Belleza Yantra /Yantra Beauty Clinic',NULL);
COMMIT;