INSERT INTO TIPO_ERROR (Cve,Descripcion) VALUES (
'AcceptedValues','CATÁLOGO');
INSERT INTO TIPO_ERROR (Cve,Descripcion) VALUES (
'DataType','TIPO DE DATO INCORRECTO, SIGNOS ESPECIALES NO ACEPTADOS');
INSERT INTO TIPO_ERROR (Cve,Descripcion) VALUES (
'DateFormat','FORMATO DE FECHA INCORRECTO');
INSERT INTO TIPO_ERROR (Cve,Descripcion) VALUES (
'NotBlank','REQUERIDO');
INSERT INTO TIPO_ERROR (Cve,Descripcion) VALUES (
'NotNull','REQUERIDO');
INSERT INTO TIPO_ERROR (Cve,Descripcion) VALUES (
'Past','FECHA INCORRECTA');
INSERT INTO TIPO_ERROR (Cve,Descripcion) VALUES (
'Pattern','CARACTERES ESPECIALES');
INSERT INTO TIPO_ERROR (Cve,Descripcion) VALUES (
'Read','ERROR DE LECTURA DE LÍNEA');
INSERT INTO TIPO_ERROR (Cve,Descripcion) VALUES (
'Rules','ERROR DE CONCISTENCIA');
INSERT INTO TIPO_ERROR (Cve,Descripcion) VALUES (
'Size','LONGITUD INVÁLIDA');
COMMIT;
